version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/London'
      WEBPASSWORD: '@R9a=+v(Xkg9%,[W'
    # Volumes store your data between container upgrades
    networks:
      steep-corner-net:
        ipv4_address: 192.168.1.3
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  steep-corner-net:
    external:
      name: sc-net


#sudo docker network create -d macvlan --subnet=192.168.1.0/24 --gateway=192.168.1.1  -o parent=eth0 sc-net